version: "3.8"

networks:
    ebike:

services:
    nginx:
        build:
            context: ./eBike-backend-laravel
            dockerfile: nginx.dockerfile
        ports:
            - "80:80"
        container_name: "nginx"
        volumes:
            - ./eBike-backend-laravel/backend:/var/www/html
        restart:
            "always"
        networks:
            ebike:
        depends_on:
            - php
            - ebike_backend

    php:
        build:
            context: ./eBike-backend-laravel
            dockerfile: php.dockerfile
        container_name: "php"
        networks:
            ebike:
        volumes:
            - ./eBike-backend-laravel/backend:/var/www/html

    composer:
        build:
            context: ./eBike-backend-laravel
            dockerfile: composer.dockerfile
        container_name: "composer"
        networks:
            ebike:
        volumes:
            - ./eBike-backend-laravel/backend:/var/www/html
        working_dir: /var/www/html

    npm:
        image: node:current-alpine
        container_name: "npm"
        networks:
            ebike:
        volumes:
            - ./eBike-backend-laravel/backend:/var/www/html
        entrypoint: [ "npm" ]
        working_dir: /var/www/html

    artisan:
        build:
            context: ./eBike-backend-laravel
            dockerfile: php.dockerfile
        container_name: "artisan"
        networks:
            ebike:
        volumes:
            - ./eBike-backend-laravel/backend:/var/www/html
        working_dir: /var/www/html
        entrypoint: [ "php", "/var/www/html/artisan" ]

    ebike_seed:
        build:
            context: eBike-backend-laravel
            dockerfile: seed.dockerfile
        env_file:
            - .env
        image: ebike/seed:latest
        container_name: "seed"

    ebike_backend:
        build:
            context: ./eBike-backend-laravel
            dockerfile: backend.dockerfile
        env_file:
          - .env
        container_name: "ebike_backend"
        ports:
            - "8000:8000"
        restart:
            "always"
        networks:
            ebike:

    ebike_simulator:
        build:
            context: ./eBike-controlsys-python
            dockerfile: Dockerfile
        image: ebike/bike_simulator:latest
        container_name: "bike_simulator"
        networks:
            ebike:
        depends_on:
            - ebike_backend

    ebike_frontend:
        build:
            context: ./eBike-frontend-react
            dockerfile: Dockerfile
        env_file:
            - .env
        image: ebike/frontend:latest
        container_name: "bike_frontend"
        ports:
            - "3000:3000"
        networks:
            ebike:
        restart:
            "always"
        depends_on:
            - ebike_backend
