version: "3.8"

networks:
    ebike:

services:
    nginx:
        build:
            context: ./eBike-backend-laravel
            dockerfile: nginx.dockerfile
        container_name: "nginx"
        ports:
            - "1337:1337"
        volumes:
            - ./eBike-backend-laravel/backend:/var/www/html
        networks:
            - ebike
        restart: "always"
        depends_on:
            - mysql
            - php

    mysql:
        image: mysql:8.0
        container_name: "mysql"
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - ebike
        volumes:
            - ./eBike-backend-laravel/mysql:/var/lib/mysql

    php:
        build:
            context: ./eBike-backend-laravel
            dockerfile: php.dockerfile
        container_name: "php"
        networks:
            - ebike
        volumes:
            - ./eBike-backend-laravel/backend:/var/www/html
        depends_on:
            - mysql

    composer:
        build:
            context: ./eBike-backend-laravel
            dockerfile: composer.dockerfile
        container_name: "composer"
        networks:
            - ebike
        volumes:
            - ./eBike-backend-laravel/backend:/var/www/html
        working_dir: /var/www/html

    npm:
        image: node:current-alpine
        container_name: "npm"
        networks:
            - ebike
        volumes:
            - ./eBike-backend-laravel/backend:/var/www/html
        entrypoint: [ "npm" ]
        working_dir: /var/www/html

    artisan:
        build:
            context: ./eBike-backend-laravel
            dockerfile: php.dockerfile
        container_name: "artisan"
        networks:
            - ebike
        volumes:
            - ./eBike-backend-laravel/backend:/var/www/html
        working_dir: /var/www/html
        entrypoint: [ "php", "/var/www/html/artisan" ]

#    ebike_seed:
#        build:
#            context: ./eBike-backend-laravel
#            dockerfile: seed.dockerfile
#        container_name: "seed"
#        env_file:
#            - .env
#        image: ebike/seed:latest

    ebike_backend:
        build:
            context: ./eBike-backend-laravel
            dockerfile: backend.dockerfile
#        env_file:
#          - ./eBike-backend-laravel/backend/.env
        container_name: "ebike_backend"
        ports:
            - "8000:8000"
        networks:
            - ebike
        volumes:
            - ./eBike-backend-laravel/backend:/var/www/html

    ebike_simulator:
        build:
            context: ./eBike-controlsys-python
            dockerfile: Dockerfile
        image: ebike/bike_simulator:latest
        container_name: "bike_simulator"
        networks:
            - ebike
        depends_on:
            - ebike_backend

    ebike_frontend:
        build:
            context: ./eBike-frontend-react
            dockerfile: Dockerfile
        env_file:
            - .env
        image: ebike/frontend:latest
        container_name: "bike_frontend"
        ports:
            - "3000:3000"
        networks:
            - ebike
        restart:
            "always"
        depends_on:
            - ebike_backend
